### PR TITLE
Add support for field preproc on updates

### LINKED ISSUE #2: Fields gets processed for writes on create but not update
There is a `_processFieldsForWrites` function which handles calling preprocessing logic for fields when writing data. It is set up to run on `createObject` method (https://github.com/WorldBrain/storex-backend-dexie/blob/master/ts/index.ts#L140), but not on `updateObjects` method.

### PR DESCRIPTION
**Pull request by poltak**
- fixes #2 
- seems to fix the issue in Memex
- doesn't support all update ops yet, just picked out some common ones like `$set`, `$inc`, etc
- see f0d0557 for more info

### CODE REVIEW

**Comment by ShishKabab** [comment]
Looks good  :)  One thing though is the removal of await for the stemmer. Was thinking here that in the future the stemmer might run in it's own thread.

Also, through your PR I notice that I didn't think of in-place updates for Storex. The way I'm using it in the Auth service just assumes everything in updateObject() is a $set. Will need to change that in the Auth service, but it's a good thing to have for databases that support atomic operations (Redis for example.)

**Comment by poltak** [comment]
> One thing though is the removal of await for the stemmer. Was thinking here that in the future the stemmer might run in it's own thread

I see. I actually updated that a while back in bb4419136143b7514dd05232136b0227efab66cb, although noticed that I forgot some parts of it in here hence that commit to remove them. I originally thought it was a mistake which is why I changed it, but can easily change those back if desired. 

So, given that the function exported from the `memex-stemmer` is a standard non async/Promise-returning function, am I right in understanding that if you `await` the calls in an async function it will add another tick to the event loop (something like doing a `setTimeout(fn, 0)`?

**Comment by ShishKabab** [comment]
No idea actually how it's implemented under the hood... Only recently discovered you a) can await everything, without needing to check whether it's a promise, and b) you can return promises directly from async functions without awaiting then first (thought that'd return a Promise<Promise<any>>  :P  )

Would the extra tick be a problem? I think there's some generator based stuff underneath the hoods when compiled with Babel, and I imagine that involves some type checking and maybe returning immediately if possible. No idea about the native browsers' async/await implementations though..

**Comment by poltak** [comment]
> Would the extra tick be a problem?

No I don't see any reason it would be, apart from some really obscure timing edge-cases. But I don't actually know if it would do that; I was more asking the question in-case you knew :P it is all so confusing what's actually going on in the browser with the whole tsc->babel multi-step transpilation that happens.

> Only recently discovered ... you can return promises directly from async functions without awaiting then first

Yeah but I recently found out (thanks to a [linting rule](https://github.com/eslint/eslint/issues/7537)) a `return await myPromise` is treated slightly different to a `return myPromise` from an async fn (I suppose ignoring any tsc/babel stuff going on in the middle - not sure if they handle it specifically).

**Pull request merged**
